### ISSUE TITLE
[Enhancement]: Refactor fixture_teardown

### ISSUE THREAD

**Issue by Faakhir30** [destrex271/pgweb-testing-harness#34]
Hi, @destrex271 , currently all functional tests are using exactly same _fixtures_teardown as internal module function. I would like to refactor it to `extra_utils/util_functions.py` as the teardown logic is independent of the testcase module.

If you can share your thoughts on this, I would love to contribute more

**Comment by destrex271** [comment]
Yes! That would be fantastic.

**Comment by Faakhir30** [comment]
Solved in #36
