### ISSUE TITLE
[Enhancement]: Ability to add diferent depths for internal and external links

### ISSUE THREAD

**Issue by Faakhir30** [destrex271/pgweb-testing-harness#35]
Hi @destrex271,  I worked on a custom crawler some time ago, however, I've noticed that we don't need to check for broken links in external links for as large depths as we would prefer to check for internal links.

Therefore, I would like to add the ability to crawl internal and external links to different depths. If you could share your thoughts on this, I would like to do this myself.

**Comment by destrex271** [comment]
Sure this will be much better.
